# Generated by Django 5.0.7 on 2024-07-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('bairro', models.TextField(max_length=255)),
                ('sexo', models.TextField(max_length=10)),
                ('cidade', models.TextField(max_length=255)),
            ],
        ),
    ]
