# Generated by Django 5.0.7 on 2024-08-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_encontro'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontro',
            name='horario',
            field=models.TimeField(default='00:00'),
        ),
    ]
